<a href="https://colab.research.google.com/github/MuhammadShaheer-khan/Logistic-Regression-Models/blob/master/Targeting_Customers_Through_Ads.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Logistic Regression Model

In [100]:
# iMPORTING libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [101]:
from google.colab import files
uploaded = files.upload()
import io
SNA_data = pd.read_csv(io.BytesIO(uploaded['Social_Network_Ads.csv']))

Saving Social_Network_Ads.csv to Social_Network_Ads (1).csv


In [102]:
SNA_data.head(10)

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0
5  15728773    Male   27            58000          0
6  15598044  Female   27            84000          0
7  15694829  Female   32           150000          1
8  15600575    Male   25            33000          0
9  15727311  Female   35            65000          0

In [103]:
SNA_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [112]:
x = SNA_data.iloc[:,[2,3]].values
y = SNA_data.iloc[:,4].values

In [113]:
print(x[:5])
print("-----------")
print(x[:5])

[[   19 19000]
 [   35 20000]
 [   26 43000]
 [   27 57000]
 [   19 76000]]
-----------
[[   19 19000]
 [   35 20000]
 [   26 43000]
 [   27 57000]
 [   19 76000]]


In [114]:
# Split data into Test and Train

from sklearn.model_selection import train_test_split

train_x,train_y,test_x,test_y = train_test_split(x, y, test_size = 0.25, random_state = 0)

In [115]:
train_x[:5]

array([[    44,  39000],
       [    32, 120000],
       [    38,  50000],
       [    32, 135000],
       [    52,  21000]])

In [116]:
train_y[:5]

array([[   30, 87000],
       [   38, 50000],
       [   35, 75000],
       [   30, 79000],
       [   35, 50000]])

In [117]:
test_x[:5]

array([0, 1, 0, 1, 1])

In [118]:
test_y[:5]

array([0, 0, 0, 0, 0])

In [119]:
# Feature Scaling for convert data between -2 to 2

from sklearn.preprocessing import StandardScaler

std = StandardScaler()
train_x = std.fit_transform(train_x)
test_x  = std.fit_transform(test_x)

ValueError: ignored

In [120]:
train_x.shape

(300, 2)

In [121]:
test_x.shape

(300,)

In [122]:
# Import Logistic Regression

from sklearn.linear_model import LogisticRegression

Lr = LogisticRegression(random_state = 0)
Lr.fit(train_x,train_y)

ValueError: ignored